In [6]:
import numpy as np
import pandas as pd

df = pd.read_csv("/mnt/d/storage2/Salaries.csv")
print(df)

     Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
0             1      Prof          B             19           18  Male  139750
1             2      Prof          B             20           16  Male  173200
2             3  AsstProf          B              4            3  Male   79750
3             4      Prof          B             45           39  Male  115000
4             5      Prof          B             40           41  Male  141500
..          ...       ...        ...            ...          ...   ...     ...
392         393      Prof          A             33           30  Male  103106
393         394      Prof          A             31           19  Male  150564
394         395      Prof          A             42           25  Male  101738
395         396      Prof          A             25           15  Male   95329
396         397  AsstProf          A              8            4  Male   81035

[397 rows x 7 columns]


In [9]:
print(df.size)

2779


In [10]:
print(df.head)

<bound method NDFrame.head of      Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
0             1      Prof          B             19           18  Male  139750
1             2      Prof          B             20           16  Male  173200
2             3  AsstProf          B              4            3  Male   79750
3             4      Prof          B             45           39  Male  115000
4             5      Prof          B             40           41  Male  141500
..          ...       ...        ...            ...          ...   ...     ...
392         393      Prof          A             33           30  Male  103106
393         394      Prof          A             31           19  Male  150564
394         395      Prof          A             42           25  Male  101738
395         396      Prof          A             25           15  Male   95329
396         397  AsstProf          A              8            4  Male   81035

[397 rows x 7 columns

In [30]:
# df['salary'].describe()
df['salary'].count()

397

In [17]:
distance = [10,15,17,26]
time= [0.3,0.47,0.55,1.28]
import numpy as np
npdistance = np.array(distance)
nptime= np.array(time)
npspeed = npdistance/nptime
# print(npspeed)
npspeed

array([33.33333333, 31.91489362, 30.90909091, 20.3125    ])

In [22]:
city = np.array(['nyc','london','delhi','kashi'])
city.ndim
# city.shape

1

In [21]:
city.shape

(4,)

In [24]:
# basic operations on an array
first = [10,20,30,40]
second = [12,11,21,24]
npfirst = np.array(first)
npsecond = np.array(second)
npfirst+npsecond
# print(npfirst+npsecond)

array([22, 31, 51, 64])

In [16]:
distance2d = ([10,20,30,40],[12,11,21,24])
# distance2d
distancefirst = distance2d[0]
print(distancefirst)
distacesecond = distance2d[1]
print(distacesecond)

[10, 20, 30, 40]
[12, 11, 21, 24]


In [34]:
import numpy as np
test_scores = np.array([[83,71,57,63],[54,68,81,45]])
pass_score = test_scores > 60
pass_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [36]:
test_scores[pass_score]
# print(test_scores[pass_score])

[83 71 63 68 81]


In [37]:
city = np.array(['nyc','london','delhi','kashi'])
newcity = city
newcity is city

True

In [38]:
len(newcity)

4

In [39]:
newcity.view()

array(['nyc', 'london', 'delhi', 'kashi'], dtype='<U6')

In [45]:
# shape manipulation in arrays in python
#  ravel ,  split , flatten , resize , reshape , stack

test_scores = np.array([[83,71,57,63],[54,68,81,45],[45,89,78,33]])
newscores = test_scores.ravel()
newscores



array([83, 71, 57, 63, 54, 68, 81, 45, 45, 89, 78, 33])

In [46]:
newscores.ndim

1

In [47]:
newscores.shape

(12,)

In [48]:
flattenscores = test_scores.flatten()
flattenscores


array([83, 71, 57, 63, 54, 68, 81, 45, 45, 89, 78, 33])

In [49]:
reshapescores = test_scores.reshape(4,3)
reshapescores

array([[83, 71, 57],
       [63, 54, 68],
       [81, 45, 45],
       [89, 78, 33]])

In [56]:
np.hsplit(flattenscores,3)

[array([83, 71, 57, 63]), array([54, 68, 81, 45]), array([45, 89, 78, 33])]

In [ ]:
stackarray = np.hstack()